### ISSUE TITLE
Browser detection on Linux slow / Chrome won't start for debug session

### ISSUE THREAD

**Issue by buzz-tee** [microsoft/vscode-js-debug-browsers#16]
When trying to debug a web application on Linux the browser detection takes very long and fails more often than not.

The `ps` command reveals a suspicious looking grep command:
```
grep -ER "^Exec=/.*/(google-chrome-unstable|google-chrome-dev|google-chrome-beta|google-chrome-canary|google-chrome-stable|google-chrome|chromium-browser|chromium)-.*" /usr/bin | awk -F '=' '{print $2}'
```

It has its origins these code fragments:
* https://github.com/microsoft/vscode-js-debug-browsers/blob/e2ee9c60faae549dd3b2b385ceecaf12282f40da/src/linuxChrome.ts#L66
* https://github.com/microsoft/vscode-js-debug-browsers/blob/e2ee9c60faae549dd3b2b385ceecaf12282f40da/src/linuxChrome.ts#L107
* https://github.com/microsoft/vscode-js-debug-browsers/blob/e2ee9c60faae549dd3b2b385ceecaf12282f40da/src/linuxChrome.ts#L119

### Slowness
My /usr/bin directory has ~6000 entries, about 2.7GB in size (not even counting symlinks...) - it is understandable that grepping these files would take some time.

### Detection fails
Shell scripts in /usr/bin cannot be expected to contain lines like `Exec=/usr/local/bin/google-chrome` (but /usr/share/applications/*.desktop files do). The relevant lines would rather look like `exec /path/to/google-chrome`.

### Proposals
1. Remove `/usr/bin` from `desktopInstallationFolders` in [L66](https://github.com/microsoft/vscode-js-debug-browsers/blob/e2ee9c60faae549dd3b2b385ceecaf12282f40da/src/linuxChrome.ts#L66)
2. It is evident that only script files should be taken into account, so excluding binary files from grep via -I (ignore binary) flag provides a speed boost at zero cost. The flag should be added to [L119](https://github.com/microsoft/vscode-js-debug-browsers/blob/e2ee9c60faae549dd3b2b385ceecaf12282f40da/src/linuxChrome.ts#L119) and [L121](https://github.com/microsoft/vscode-js-debug-browsers/blob/e2ee9c60faae549dd3b2b385ceecaf12282f40da/src/linuxChrome.ts#L121)

In the end it may be desirable to keep searching the `/usr/bin` folder. In this case it probably makes sense to devise a dedicated grep to perform on the contents of /usr/bin. The resulting invocation might look something like this, at least that works on my system:
```
grep -ERI "^exec /.*/(google-chrome-unstable|google-chrome-dev|google-chrome-beta|google-chrome-canary|google-chrome-stable|google-chrome|chromium-browser|chromium)" /usr/bin | cut -d ' ' -f 2-
```

**Comment by connor4312** [comment]
Thanks for the detailed writeup! For a conservative fix, I'll add the `I` flag to the grep pattern.
